s=set()
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
n=input("enter no. here: ")
s.add(int(n))
print(s)